version: "3"

services:
  image_scout:
    build: ./
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgres://image_scout@postgres:5432/image_scout"
      ROCKET_DATABASES: '{main={url="postgres://image_scout@postgres:5432/image_scout"}}'
      ROCKET_ADDRESS: 0.0.0.0
      TWITTER_BEARER: ${TWITTER_BEARER}

    ports:
      - 8000:8000
    command: just run
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=image_scout
      - POSTGRES_DB=image_scout
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
